#index:
#    path: /
#    controller: App\Controller\DefaultController::index

set_locale:
    path:  /setlocale/{locale}
    controller: "App\\Controller\\LocaleController::setlocaleAction"

app_login:
    path: /login
    controller: "App\\Controller\\SecurityController::login"

searchByTag:
    path:       searchByTag
    controller: App\Controller\QuestionsController::searchByTag