<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use function Sodium\add;

class LoginFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('username')
            ->add('password')
            ->add('email')
            ->add('first_name')
            ->add('last_name')
            ->add('phone_number')
            ->add('is_lawyer')
            ->add('law_licence_no');

    }

}